//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BouncyCastles.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrdersID { get; set; }
        public int CastlesID { get; set; }
        public int ClientsID { get; set; }
        public string AdrStreet { get; set; }
        public string AdrZipCode { get; set; }
        public string AdrCity { get; set; }
        public string AdrRegion { get; set; }
        public System.DateTime StartDay { get; set; }
        public System.DateTime EndDay { get; set; }
    
        public virtual Castle Castle { get; set; }
        public virtual Client Client { get; set; }
    }
}
